// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BidEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<string>("Bidder")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HouseId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HouseId");

                    b.ToTable("Bids");

                    b.HasData(
                        new
                        {
                            Id = "45ee9f64-3e72-11ed-b878-0242ac120002",
                            Amount = 200000,
                            Bidder = "Sonia Reading",
                            HouseId = "45eeb0f8-3e72-11ed-b878-0242ac120002"
                        },
                        new
                        {
                            Id = "45eea252-3e72-11ed-b878-0242ac120002",
                            Amount = 202400,
                            Bidder = "Dick Johnson",
                            HouseId = "45eeb0f8-3e72-11ed-b878-0242ac120002"
                        },
                        new
                        {
                            Id = "45eea39c-3e72-11ed-b878-0242ac120002",
                            Amount = 302400,
                            Bidder = "Mohammed Vahls",
                            HouseId = "45eeaef0-3e72-11ed-b878-0242ac120002"
                        },
                        new
                        {
                            Id = "45eea4d2-3e72-11ed-b878-0242ac120002",
                            Amount = 310500,
                            Bidder = "Jane Williams",
                            HouseId = "45eeaef0-3e72-11ed-b878-0242ac120002"
                        },
                        new
                        {
                            Id = "45eea73e-3e72-11ed-b878-0242ac120002",
                            Amount = 315400,
                            Bidder = "John Kepler",
                            HouseId = "45eeaef0-3e72-11ed-b878-0242ac120002"
                        });
                });

            modelBuilder.Entity("HouseEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Photo")
                        .HasColumnType("text");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Houses");

                    b.HasData(
                        new
                        {
                            Id = "45eeb0f8-3e72-11ed-b878-0242ac120002",
                            Address = "123 Test st, New York",
                            Country = "USA",
                            Description = "A beautiful renovated Colonial in the heart of the best City, NYC!",
                            Price = 90000
                        },
                        new
                        {
                            Id = "45eeaef0-3e72-11ed-b878-0242ac120002",
                            Address = "234 Dummy st, Brooklyn",
                            Country = "USA",
                            Description = "An amazing investment property opportunity in this two-family house",
                            Price = 12000000
                        });
                });

            modelBuilder.Entity("BidEntity", b =>
                {
                    b.HasOne("HouseEntity", "House")
                        .WithMany()
                        .HasForeignKey("HouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("House");
                });
#pragma warning restore 612, 618
        }
    }
}
