// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class HouseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.8");

            modelBuilder.Entity("BidEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bidder")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("HouseId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HouseId");

                    b.ToTable("Bids");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 200000,
                            Bidder = "Sonia Reading",
                            HouseId = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = 202400,
                            Bidder = "Dick Johnson",
                            HouseId = 1
                        },
                        new
                        {
                            Id = 3,
                            Amount = 302400,
                            Bidder = "Mohammed Vahls",
                            HouseId = 2
                        },
                        new
                        {
                            Id = 4,
                            Amount = 310500,
                            Bidder = "Jane Williams",
                            HouseId = 2
                        },
                        new
                        {
                            Id = 5,
                            Amount = 315400,
                            Bidder = "John Kepler",
                            HouseId = 2
                        });
                });

            modelBuilder.Entity("HouseEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Photo")
                        .HasColumnType("TEXT");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Houses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Test st, New York",
                            Country = "USA",
                            Description = "A beautiful renovated Colonial in the heart of the best City, NYC!",
                            Price = 90000
                        },
                        new
                        {
                            Id = 2,
                            Address = "234 Dummy st, Brooklyn",
                            Country = "USA",
                            Description = "An amazing investment property opportunity in this two-family house",
                            Price = 12000000
                        });
                });

            modelBuilder.Entity("BidEntity", b =>
                {
                    b.HasOne("HouseEntity", "House")
                        .WithMany()
                        .HasForeignKey("HouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("House");
                });
#pragma warning restore 612, 618
        }
    }
}
